### ISSUE TITLE
Documentation Suggestions

### ISSUE THREAD

**Issue by smadds** [Paul-Reed/thermostat#1]
Thanks for packaging this as a node, Paul - it's a great control.

Perhaps to make things clear to newbies you could note where to find the example - in my case it appeared on my dashboard (/ui) under an Example tab. For some reason after the instructions to move the admin page I was expecting it in the root.

Also, it's not obvious that you need to click (or touch) and hold for 1 second before you can change the set value - that caught me out!

**Comment by Paul-Reed** [comment]
Readme updated to guide users to click thermostat for 1 second before adjusting - thanks.
It's standard protocol to load example flows in their own dashboard tab, and I would expect users to be familiar with node-red before venturing into 3rd party contributions.
