### ISSUE TITLE
Request - to set Options from flow

### ISSUE THREAD

**Issue by smadds** [Paul-Reed/thermostat#2]
Sadly my JS skills are not up to doing this myself, but it would be very useful when using the gauge for other things to be able to set the min & max values etc.

My attempt by adding the following didn't redraw the dial
```
       } if (data.topic == "minvalue") {
            options.minValue = data.payload;
            render()
       } if (data.topic == "maxvalue") {
            options.maxValue = data.payload;
            render()
```

**Comment by Paul-Reed** [comment]
Most of the 'flow' inputs are controlled [here](https://github.com/Paul-Reed/thermostat/blob/master/thermojs/thermo.js#L474-L495) so you could try following those examples.
Feel free to git fork and change as you wish.
